name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

categories:
  - title: "🚀 Features"
    labels: ["feature", "enhancement"]
  - title: "🐛 Fixes"
    labels: ["bug", "fix"]
  - title: "🧰 Maintenance"
    labels: ["chore", "refactor", "docs", "ci", "build"]
  - title: "🔒 Security"
    labels: ["security"]

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/Joedaddy66/spartan-resilience-framework/compare/$PREVIOUS_TAG...$NEXT_TAG

version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor", "feature", "enhancement"]
  patch:
    labels: ["patch", "bug", "fix", "chore", "refactor", "docs", "ci", "build", "security"]
  default: patch

exclude-labels:
  - "skip-changelog"

autolabeler:
  - label: "docs"
    title:
      - "/docs/i"
  - label: "ci"
    files:
      - ".github/**"
  - label: "security"
    title:
      - "/security/i"

replacers:
  - search: '\n{3,}'
    replace: "\n\n"
