name: Publish to PyPI (token)

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine wheel setuptools

      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: 
        run: |
          python -m build
          twine upload dist/*
