name: Security Checks
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run weekly security checks
    - cron: '0 2 * * 1'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install safety bandit semgrep
          
      - name: Python Security Scan with Safety
        run: |
          echo "Running safety check for known vulnerabilities..."
          safety check --json --output safety-report.json || true
          safety check || (echo "Security vulnerabilities found in Python packages" && exit 1)
          
      - name: Static Analysis with Bandit
        run: |
          echo "Running Bandit static analysis..."
          bandit -r src/ -f json -o bandit-report.json || true
          bandit -r src/ || (echo "Security issues found in source code" && exit 1)
          
      - name: Check for hardcoded secrets
        run: |
          echo "Scanning for potential secrets..."
          grep -r -i -E "(password|passwd|pwd|secret|key|token|api_key)" src/ || echo "No obvious secrets found"
          
      - name: Verify no vulnerable requests versions
        run: |
          echo "Checking Python requests library version..."
          python -c "import requests; print(f'requests version: {requests.__version__}')"
          # Ensure we're using a recent, secure version of requests
          python -c "import requests; assert requests.__version__ >= '2.25.0', 'requests version too old'"
          
      - name: Generate Software Bill of Materials (SBOM)
        run: |
          pip install pip-audit
          pip-audit --format=json --output=sbom.json || true
          echo "SBOM generated in sbom.json"
          
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            safety-report.json
            bandit-report.json
            sbom.json